CREATE TABLE REPORTS(
                        imageUrl varchar(249),
                        timeAgo varchar(100),
                        petName varchar(100),
                        status int,
                        location varchar(100),
                        authorName varchar(100),
                        authorNickName varchar(100),
                        type int,
                        id BIGSERIAL PRIMARY KEY,
                        posted timestamp DEFAULT now(),
                        animalType varchar(100),
                        petId BIGINT,
                        latitude NUMERIC(10, 7),
                        longtitude NUMERIC(10, 7),
                        dominantColors varchar(200),
                        collarColor varchar(200),
                        breed varchar(200),
                        size varchar(200),
                        gender varchar(200),
                        tel varchar(200),
                        email varchar(200),
                        social varchar(200),
                        note varchar(200)
);
