export const CAT_BREEDS: string[] = [
  'Ragdoll',
  'Exotic Shorthair',
  'British Shorthair',
  'Persian',
  'Maine Coon',
  'American Shorthair',
  'Devon Rex',
  'Sphynx',
  'Scottish Fold',
  'Abyssinian',
  'Oriental',
  'Siamese',
  'Norwegian Forest Cat',
  'Cornish Rex',
  'Bengal',
  'Russian Blue',
  'Siberian',
  'Burmese',
  'Birman',
  'Tonkinese',
  'Ocicat',
  'Selkirk Rex',
  'Ragamuffin',
  'American Curl',
  'Japanese Bobtail',
  'Manx',
  'Egyptian Mau',
  'Somali',
  'Balinese',
  'Singapura',
  'Colorpoint Shorthair',
  'Lykoi',
  'Chartreux',
  'Turkish Angora',
  'European Burmese',
  'Bombay',
  'Khao Manee',
  'Burmilla',
  'Korat',
  'American Bobtail',
  'Havana Brown',
  'LaPerm',
  'Turkish Van',
  'American Wirehair',
  'California Spangled',
  'Cymric',
  'Himalayan',
  'Munchkin',
  'Nebelung',
  'Pixie-bob',
  'Savannah',
  'Snowshoe',
  'Toyger',
  'York Chocolate',
  'Aegean',
  'Australian Mist',
  'American Polydactyl',
  'Arabian Mau',
  'Asian cat',
  'Asian Semi-longhair',
  'Bambino',
  'Brazilian Shorthair',
  'British Longhair',
  'Chantilly-Tiffany',
  'Chausie',
  'Cheetoh',
  'Cyprus',
  'Javanese',
  'Donskoy',
  'Peterbald',
  'Ukrainian Levkoy',
  'Elf cat',
  'Dwelf',
  'Sokoke',
  'Minskin',
  'Serengeti cat',
  'Napoleon cat',
  'Thai cat',
  'Unknown',
];
