export const DOG_BREEDS: string[] = [
  'Afador',
  'Afaird',
  'Affen Spaniel',
  'Affen Border Terrier',
  'Affen Tzu',
  'Affenchon',
  'Affengriffon',
  'Affenhuahua',
  'Affenpinscher',
  'Affenpoo',
  'Affenpug',
  'Affenshire',
  'Affenwich',
  'Afghan Chon',
  'Afghan Collie',
  'Afghan Gaddi',
  'Afghan Hound',
  'Afghan Retriever',
  'Afghan Sheepdog',
  'Afghan Spaniel',
  'African-American Bull Boerboel',
  'African Pitbull',
  'Afollie',
  'African Wild Dog',
  'Africanis',
  'Aidi',
  'Ainu Dog',
  'Airedale Shepherd',
  'Airedale Terrier',
  'Airedoodle',
  'Akbash Dog',
  'Akbash Pyrenees',
  'Akbash Rottie',
  'Aki-Poo',
  'Akita (American)',
  'Akita Basset',
  'Akita Bernard',
  'Akita Chow',
  'Akita Inu (Japanese)',
  'Akita Pit',
  'Akita Shepherd',
  'Akitamatian',
  'Alano Español',
  'Alapaha Blue Blood Bulldog',
  'Alaskan Goldenmute',
  'Alaskan Husky',
  'Alaskan Husky Shepherd',
  'Alaskan Klee Kai',
  'Alaskan Malador',
  'Alaskan Malamute',
  'Alaskan Shepherd',
  'Alaskan Weimsky',
  'Alaunt',
  'Alopekis',
  'Alpine Dachsbracke',
  'Alpine Mastiff',
  'Alpine Spaniel',
  'Alusky',
  'Ambullneo Mastiff',
  'American Allaunt',
  'American Alsatian',
  'American Bandogge Mastiff',
  'American Blue Gascon Hound',
  'American Blue Lacy',
  'American Boston Bull Terrier',
  'American Boxer Foxhound',
  'American Bull-Aussie',
  'American Bull Dane',
  'American Bull Dogue de Bordeaux',
  'American Bull Mastiff',
  'American Bull Molosser',
  'American Bull Pei',
  'American Bull Staffy',
  'American Bullador',
  'American Bulldog',
  'American Bulldog Shepherd',
  'American Bullhuahua',
  'American Bullnese',
  'American Bullweiler',
  'American Bully',
  'American Cocker Spaniel',
  'American Eagle Dog',
  'American English Coonhound',
  'American Eskimo Dog',
  'American Foxeagle',
  'American Foxhound',
  'American French Bull Terrier',
  'American French Bulldog',
  'American Gointer',
  'American Hairless Min Pin',
  'American Hairless Terrier',
  'American Indian Dog',
  'American Lab Foxhound',
  'American Leopard Hound',
  'American Lo-Sze Pugg ™',
  'American Mastiff',
  'American Mastiff (Panja)',
  'American Neo Bull',
  'American Pit Bull Terrier',
  'American Pit Corso',
  'American Pugabull',
  'American Rat Pinscher',
  'American Staffordshire Bully',
  'American Staffordshire Terrier',
  'American Staffy Bullmastiff',
  'American Treeing Feist',
  'American Water Spaniel',
  'American White Shepherd',
  'Amitola Bulldog',
  'Amstiff',
  'Anangu',
  'Anatolian Pyrenees',
  'Anatolian Shepherd Dog',
  'Andalusian Podenco',
  'Appenzell Mountain Dog',
  'Ariegeois',
  'Armenian Gampr',
  'Arubian Cunucu Dog',
  'Aspin',
  'Atlas Terrier',
  'Ausahoula',
  'Ausky',
  'Aussalier',
  'Aussie Brittany',
  'Aussie-Chi',
  'Aussie Collie',
  'Aussie-Corgi',
  'Aussiedoodle',
  'Aussiedor',
  'Aussie-Flat',
  'Aussie Jack',
  'Aussie Malamute',
  'Aussie Newfie',
  'Aussie Rottie',
  'Aussie Shiba',
  'Aussie Siberian',
  'Aussie Springer',
  'Auss-Tzu',
  'Austi-Pap',
  'Australian Bandog',
  'Australian Boxherd',
  'Australian Bulldog',
  'Australian Cattle Dog',
  'Australian Cobberdog',
  'Australian Eskimo',
  'Australian Kelpie',
  'Australian Labradoodle',
  'Australian Retriever',
  'Australian Shepherd',
  'Aussie Silk Terrier',
  'Australian Stumpy Tail Cattle Dog',
  'Australian Terrier',
  'Australian Yorkshire Terrier',
  'Austrian Shorthaired Pinscher',
  'Azawakh',
  'Azawakh Borzoi',
  'Bagle Hound',
  'Bakharwal Dog',
  'Bando Bull',
  'Banter Bulldogge',
  'Barbet',
  'Barger Stock Feist',
  'Bascottie',
  'Basenji',
  'Basenji Pit',
  'Ba-Shar',
  'Baskimo',
  'Bassador',
  'Basschshund',
  'Basselier',
  'Basset Artesien Normand',
  'Basset Bleu de Gascogne',
  'Basset Bluetick',
  'Basset Bordeaux',
  'Basset Fauve de Bretagne',
  'Basset Foxhound',
  'Basset Heeler',
  'Basset Hound',
  'Basset Jack',
  'Basset Retriever',
  'Basset Shepherd',
  'Bassetoodle',
  'Bassky',
  'Bassmatian',
  'Basston',
  'Bassugg',
  'Bavarian Mountain Scent Hound',
  'Bea Griffon',
  'Beabull',
  'Beagi',
  'Beagle',
  'Beagle Chin',
  'Beagle Harrier',
  'Beagle Heeler',
  'Beagleman',
  'Beaglemation',
  'Beagle Pit',
  'Beagle Point',
  'Beagle Sheltie',
  'Beagle Shepherd',
  'Beaglier',
  'Beago',
  'Be-Apso',
  'Bearded Collie',
  'Beaski',
  'Bea-Tzu',
  'Beauceron',
  'Bebasset Bordeaux',
  'Bedlington Terrier',
  'Bedlington Whippet',
  'Belgian Griffon',
  'Belgian Mastiff',
  'Belgian Shepadoodle',
  'Belgian Shepherd Groenendael',
  'Belgian Shepherd Laekenois',
  'Belgian Shepherd Malinois',
  'Belgian Shepherd Tervuren',
  'Belgrade Terrier',
  'Belusky',
  'Bergamasco',
  'Berger Blanc Suisse',
  'Berger de Picard',
  'Bernedoodle',
  'Bernefie',
  'Berner Chow',
  'Bernese Mountain Dog',
  'Bernese Rottie',
  'Bichomo',
  'Bichon Frise',
  'Bichon Yorkie',
  'Bichon-A-Ranian',
  'Bich-poo',
  'Biewer',
  'Billy',
  'Biro',
  'Biton',
  'Black and Tan Coonhound',
  'Black and Tan Coonoodle',
  'Black and Tan Coonshepherd',
  'Black and Tan Labhound',
  'Black Mouth Cur',
  'Black and Tan Coonoodle',
  'Black Mouth Pom Cur',
  'Black Norwegian Elkhound',
  'Black Russian Terrier',
  'Black Russian Wolfhound Terrier',
  'Bleu de Gascogne',
  'Bloodhound',
  'Blue Lacy',
  'Blue Picardy Spaniel',
  'Blue Paul Terrier',
  'Blue Spaniel',
  'Blue-Tzu Heeler',
  'Bluetick Coonhound',
  'Bluetick Coonhound Harrier',
  'Bluetick Walker',
  'Bocker',
  'Bo-Dach',
  'Bodacion',
  'Boerboel',
  'Boerboel Bernard',
  'Boerboel Pei',
  'Boerboel Pit',
  'Bogle',
  'Boglen Terrier',
  'Bohemian Shepherd',
  'Bo-Jack',
  'Bolo-chi',
  'Bolo-Tzu',
  'Bologco',
  'Bolognese',
  'Bolonoodle',
  'Bonsai Bulldogge',
  'Borador',
  'Border Akbash Collie',
  'Border Akita Collie',
  'Border-Aussie',
  'Border Aussie Terrollie',
  'Border Basset',
  'Border Beagle',
  'Border Bluetick Collie',
  'Border Chow',
  'Border Collie',
  'Border Collie Bernard',
  'Border Collie Britt',
  'Border Collie Cocker',
  'Border Collie Pit',
  'Border Collie Pyrenees',
  'Border Heeler',
  'Border Jack',
  'Border Kelpie',
  'Border Malamute Collie',
  'Border Malamute Terrier',
  'Border Newfie',
  'Border Point',
  'Border Pom',
  'Border Rottie',
  'Border Schnollie',
  'Border Sheepdog',
  'Border Shepherd',
  'Border Springer',
  'Border Stack',
  'Border Terrier',
  'Border Whipollie',
  'Bordernese',
  'Bordoodle',
  'Borgi',
  'Borollie',
  'Borzoi',
  'Bosapso',
  'BoShih',
  'Boskimo',
  'Bosmaraner',
  'Bospin',
  'Bossi-Poo',
  'Bossie',
  'Bostalian',
  'Bostchon',
  'Bostie',
  'Bostillon',
  'Bostinese',
  'Boston Border Collie',
  'Boston Boxer',
  'Boston Cattle Dog',
  'Boston Chin',
  'Boston Huahua',
  'Boston Lab',
  'Boston Mastiff Terrier',
  'Boston Spaniel',
  'Boston Terrier',
  'Boston Yorkie',
  'Bouvier des Flandres',
  'Boweimar',
  'Bowzer',
  'Box Heeler',
  'Boxachi',
  'Boxador',
  'Boxane',
  'Boxapoint',
  'Box-a-Shar',
  'Boxer',
  'Boxer Basset',
  'Boxer Bloodhound',
  'Boxer Chow',
  'Boxer Jack',
  'Boxer Shepherd',
  'Boxer Whippet',
  'Boxerdoodle',
  'Boxerman',
  'Boxita',
  'Boxollie',
  'Boxsky',
  'Boxspring',
  'Boxweiler',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Braque De Puy',
  'Braque du Bourbonnais',
  'Brat',
  'Brazilian Terrier',
  'Briard',
  'Briquet',
  'Brittany Beagle',
  'Brittany Bourbonnais',
  'Brittany Spaniel',
  'Broholmer',
  'Broodle Griffon',
  'Brottweiler',
  'Brug',
  'Brussalier',
  'Brusselranian',
  'Brusston',
  'BT Walker',
  'Buckley Mountain Feist',
  'Bugg',
  'Bukovina Sheepdog',
  'Buldogue Campeiro',
  'Bulgarian Shepherd Dog',
  'Bull Arab',
  'Bull Greyhound Terrier',
  'Bull Heeler Terrier',
  'Bull Jack',
  'Bull Mastweiler',
  'Bull Terrier',
  'Bullador',
  'Bull-Aussie',
  'Bullbasset Mastiff',
  'Bullboxer',
  'Bull-Boxer',
  'Bullboxer Pit',
  'Bullboxer Staff',
  'Bullboxer Staffy Bull',
  'Bulldog',
  'Bullenbeisser',
  'Bullmasador',
  'Bullmastiff',
  'Bullmastiff Shepherd',
  'Bullmatian',
  'Bullmatian Terrier',
  'Bulloxer',
  'Bull Chow Terrier',
  'Bull-Pei',
  'Bullwhip',
  'Bully Basset',
  'Bully Bordeaux',
  'Bully Chi',
  'Bully Kutta Lab',
  'Bully Pitsky',
  'Bully Wheaten',
  'Bullypit',
  'Bushland Terrier',
  'Cadoodle',
  'Cairanian',
  'Cairland Terrier',
  'Cairmal',
  'Cairn Beagle',
  'Cairn Chin',
  'Cairn Corgi',
  'Cairn Terrier',
  'Cairnese',
  'Cairnoodle',
  'Cairnwich Terrier',
  'Cairoston',
  'Cajun Squirrel Dog',
  'Cambodian Razorback Dog',
  'Canaan Dog',
  'Canadian Cur',
  'Canadian Eskimo Dog',
  'Canadian Inuit Dog',
  'Cane Corso Italiano',
  'Canis Panther',
  'Canoe Dog ',
  'Cão de Fila da Terceira',
  'Cão da Serra da Estrela',
  'Cão de Castro Laboreiro',
  'Cão de Fila de São Miguel',
  'Cão dos Mourey',
  'Caravan Hound',
  'Cardigan Corgi Pointer',
  'Cardigan Welsh Corgi',
  'Care-Tzu',
  'Carkie',
  'Carlin Pinscher',
  'Carnauzer',
  'Carolina Dog',
  'Carpathian Sheepdog',
  'Catahoula Bulldog',
  'Catahoula Dane',
  'Catahoula English Bulldog',
  'Catahoula Heeler',
  'Catahoula Rottie',
  'Catahoula Whippet',
  'Catalan Sheepdog',
  'Cattle Collie Dog',
  'Cattle Shepherd',
  'Caucasian Husky',
  'Caucasian Shepherd',
  'Caucasian Staffy Bull',
  'Cava-Chin',
  'Cavachon',
  'Cava-Corgi',
  'Cavador',
  'Cavalier King Charles Spaniel',
  'Cava-lon',
  'Cav-A-Malt',
  'Cav-A-Mo',
  'Cavanese',
  'Cavapom',
  'Cavapoo',
  'Cava-Shell',
  'Cavaton',
  'Cava-Tzu',
  'Cavestie',
  'Cavottish',
  'Central Asian Ovtcharka',
  'Cesky Fousek',
  'Cesky Terrier',
  'Chabrador',
  'Chacy Ranior',
  'Charlie Feist',
  'Chart Polski',
  'Chatham Hill Retriever',
  'Chatterdale',
  'Cheagle',
  'Cheeks',
  'Cheenese',
  'Cherokee Monarch',
  'Chesa-Poo',
  'Chesador',
  'Chesapeake Bay Retriever',
  'Chestie',
  'Chi Apso',
  'Chi Staffy Bull',
  'Chi-Chi',
  'Chi-Chon',
  'Chidale',
  'Chien-gris',
  'Chigi',
  'Chihuahua',
  'Chilier',
  'Chimation',
  'China Jack',
  'Chinaranian',
  'Chineranian',
  'Chinese Chongqing Dog',
  'Chinese Crested',
  'Chinese Crestepoo',
  'Chinese Foo Dog',
  'Chinese Frise',
  'Chinese Imperial Dog',
  'Chin-Ocker',
  'Chinook',
  'Chin-Pin',
  'Chin-wa',
  'Chion',
  'Chipin',
  'Chipit',
  'Chi-Poo',
  'Chippiparai',
  'Chisenji',
  'Chi-Rat',
  'Chi-Spaniel',
  'Chiweenie',
  'Chiwoxy',
  'Chizer',
  'Chongqing Hound',
  'Chonzer',
  'Chorkie',
  'Chow Chow',
  'Chow Hound Basset',
  'Chow Pei',
  'Chowpit',
  'Chow Shepherd',
  'Chug',
  'Chusky',
  'Chussel',
  'Cierny Sery',
  'Cimarron Uruguayo',
  'Cirneco Dell Etna',
  'Clydesdale Terrier',
  'Clumber Lab',
  'Clumber Pei',
  'Clumber Spaniel',
  'Clumberstiff',
  'Cluminger Spaniel',
  'Cock-A-Chon',
  'Cockalier',
  'Cock-A-Mo',
  'Cockapin',
  'Cockapoo',
  'Cock-A-Tzu',
  'Cocker Chow',
  'Cocker Griffon',
  'Cocker Jack',
  'Cocker Pug',
  'Cocker Spaniel',
  'Cocker Weim',
  'Cocker Westie',
  'Cocker Wheaten',
  'Cockeranian',
  'Cocker-Pei',
  'Cockinese',
  'Cojack',
  'Collie (Rough and Smooth)',
  'Colonial Cocker Spaniel',
  'Colorado Bulldog',
  'Combai',
  'Confetti Australian Shepherd',
  'Continental Bulldog',
  'Copica',
  'Cordoba Fighting Dog',
  'Corgi',
  'Corgi Basset',
  'Corgi Bichon',
  'Corgi Cattle Dog',
  'Corgi-Flat',
  'Corgi Pit',
  'Corgi Pointer',
  'Corgi Pug',
  'Corgi Schip',
  'Corgidor',
  'Corgipoo',
  'Corgiranian',
  'Corillon',
  'Corkie',
  'Corman Shepherd',
  'Cosheltie',
  'Coton Bolonka',
  'Coton de Tulear',
  'Coton Eskimo',
  'Coton Tzu',
  'Cotonese',
  'Cotralian',
  'Coydog',
  'Crested Apso',
  'Crested Beagle',
  'Crested Boxer',
  'Crested Cavalier',
  'Crested Havanese',
  'Crested Malt',
  'Crested Peke',
  'Crested Schnauzer',
  'Crested Tzu',
  'Crested Westie',
  'Crestoxie',
  'Cretan Hound',
  'Croatian Sheepdog',
  'Croatian Sheepsky',
  'Crustie',
  'Cumberland Sheepdog',
  'Curly-Coated Retriever',
  'Czechoslovakian Wolfdog',
  'Dach-Griffon',
  'Dachsador',
  'Dachshund',
  'Dachsi Apso',
  'Dachsweiler',
  'Daisy Dog',
  'Dakotah Shepherd',
  'Dalmadoodle',
  'Dalmador',
  'Dalmatian',
  'Dalmatian Feist',
  'Dalmatian Heeler',
  'Dalmatian Husky',
  'Dameranian',
  'Dandie Dinmont Terrier',
  'Daniff',
  'Danish-Swedish Farmdog',
  'Dashalier',
  'Daug',
  'Decker Brat',
  'Decker Hunting Terrier',
  'Deerhound Shepherd',
  'Denmark Feist',
  'Deutsch Drahthaar ',
  'Deutscher Wachtelhund',
  'Dingo',
  'Dingo Kelpie',
  'Dingo Podenco',
  'Dire Wolf',
  'Doberdor',
  'Doberman Bulldog',
  'Doberman Pinscher',
  'Doberman Pit',
  'Doberman Shepherd',
  'Dobie-Basset',
  'Dobie Foxhound',
  'Dobie Heeler',
  'Dobie Schnauzer',
  'Dobieton',
  'Dobocker',
  'Docker',
  'Dogo Argentino',
  'Dogo Cubano',
  'Dogo Pit',
  'Dogue Brasileiro',
  'Dogue de Bordeaux',
  'Domitius Maximus Mastiff',
  'Doodleman Pinscher',
  'Dorgi',
  'Dorkie',
  'Dorset Olde Tyme Bulldogge',
  'Double Doodle',
  'Doubull-Mastiff',
  'Doxie Cairn',
  'Doxie-Chin',
  'Doxie-Chon',
  'Doxie Heeler',
  'Doxiemo',
  'Doxie-Pin',
  'Doxiepoo',
  'Doxie Scot',
  'Doxle',
  'Drentse Patrijshond',
  'Drever',
  'Dutch Shepherd Dog',
  'Dutch Smoushond',
  'Dutchie Chow Shepherd',
  'East-European Shepherd',
  'East Siberian Laika',
  'Elk-a-Bee',
  'Elkhound Shepherd',
  'Elk-Kee',
  'Enga-Apso',
  'Engachon',
  'EngAm Bulldog / Olde Bulldog',
  'Eng-A-Poo',
  'Engatzu Spaniel',
  'Englian Mastiff',
  'English Boodle',
  'English Boston-Bulldog',
  'English Boxetter',
  'English Bull Springer',
  'English Bull Terrier Pit',
  'English Bullamute',
  'English Bulltyme',
  'English Bullweiler',
  'English Bully Staffy Bull Terrier',
  'English Catahoula Shepherd',
  'English Cocker Spaniel',
  'English Collie Shepherd',
  'English Coon Rottie',
  'English Cotralian',
  'English Foxhound',
  'English King',
  'English Mastweiler',
  'English Mini Foxker',
  'English Presa Bulldog',
  'English Setter',
  'English Shepherd',
  'English Speagle',
  'English Springer Spaniel',
  'English Toy Cocker Spaniel',
  'English Toy Spaniel',
  'English Water Spaniel',
  'English White Terrier',
  'Entlebucher Pit',
  'Entlebucher Sennenhund',
  'Eskapoo',
  'Eskidor',
  'Eskifon',
  'Eskijack',
  'Eskimo Chi',
  'Eskimo Chin',
  'Eskimo Pit',
  'Eskimo Schnauzer',
  'Eskimo Shepherd',
  'Eskimo Yorkie',
  'Eskland',
  'Estonian Hound',
  'Eurasier',
  'Euro Mountain Sheparnese',
  'Ewokian',
  'Farm Collie ',
  'Fauve de Bretagne',
  'Faux Frenchbo Bulldog',
  'Feist',
  'Feist Chi',
  'Feist Tzu',
  'Field Spaniel',
  'Fila Brasileiro',
  'Fila Tosa',
  'Finnish Chow Spitz',
  'Finnish Hound',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flandoodle',
  'Flat-Coated Retriever',
  'Florida Cracker Cur',
  'Foodle',
  'Formosan Mountain Dog',
  'Fo-Tzu',
  'Fourche Terrier',
  'Fox Terrier',
  'Foxhoodle',
  'Foxhound',
  'Foxingese',
  'Foxton',
  'Foxy Rat Terrier',
  'Foxy Russell',
  'Free-Lance Bulldog',
  'French Afghan Mastiff',
  'French Brittany Spaniel',
  'French Bull Jack ',
  'French Bull Terrier',
  'French Bull Tzu',
  'French Bull Weiner',
  'French Bulldog',
  'French Bullhuahua',
  'French Bullnese',
  'French Bulloxer',
  'French Pin',
  'French Bull Rat Terrier',
  'French Spaniel',
  'Frenchie Bichon',
  'Frenchie-Pei',
  'Frenchie Pug',
  'Frenchie Shepherd',
  'Frenchie Staff',
  'Frengle',
  'Galgo Español',
  'Gerberian Shepsky',
  'German Anatolian Shepherd',
  'German Australian Shepherd',
  'German Groenendael',
  'German Hunt Terrier',
  'German Longhaired Pointer',
  'German Malinois',
  'German Pinscher',
  'German Sheeppoodle',
  'German Sheltie Spitz',
  'German Shepherd Dog',
  'German Sheprador',
  'German Shorthaired Lab',
  'German Shorthaired Pointer',
  'German Spitz Giant',
  'German Spitz Medium',
  'German Spitz Shepherd',
  'German Spitz Small',
  'German Spitzpoo',
  'German Wirehaired Lab',
  'German Wirehaired Newfie',
  'German Wirehaired Pointer',
  'Giant Border Schnollie',
  'Giant Komondauzer',
  'Giant Maso Mastiff',
  'Giant Schnauzer',
  'Giant Schnoodle',
  'Glechon',
  'Glen of Imaal Terrier',
  'Goberian',
  'Golddust Yorkshire Terrier',
  'Golden Akita Retriever',
  'Golden Border Retriever',
  'Golden Boxer',
  'Golden Bulldog',
  'Golden Bullmastiff Retriever',
  'Golden Chesabay',
  'Golden Chi Retriever',
  'Golden Chow Retriever',
  'Golden Cocker Retriever',
  'Golden Dox',
  'Golden Irish',
  'Golden Jack Retriever',
  'Golden Labrador',
  'Golden Mastiff',
  'Golden Mountain Dog',
  'Golden Newfie',
  'Golden Pei',
  'Golden Pyrenees',
  'Golden Retriever',
  'Golden Rottie Retriever',
  'Golden Saint',
  'Golden Sammy',
  'Golden Sheltie',
  'Golden Shepherd',
  'Golden Tibetan Tertriever',
  'Golden Toller Retriever',
  'Goldenshire',
  'Goldendoodle',
  'Goldmaraner',
  'Goldmation',
  'Gollie',
  'Gonczy Polski',
  'Gordon Chesabay',
  'Gordondoodle',
  'Gordon Setter',
  'Gordon Sheltie',
  'Grand Basset Griffon Vendeen',
  'Grand Bleu de Gascogne',
  'Grand Fauve de Bretagne',
  'Grand Griffon Vendeen',
  'Great Bernese',
  'Great Dane',
  'Great Danebull',
  'Great Danesky',
  'Great Danoodle',
  'Great Golden Dane',
  'Great Pyredane',
  'Great Pyrenees',
  'Great Weimar',
  'Great Wolfhound',
  'Greater Swiss Mountain Dog',
  'Greek Sheepdog',
  'Greenland Dog',
  'Greyador',
  'Greyhound',
  'Greyhound Shepherd',
  'Griffairn Terrier',
  'Griffichon',
  'Griffon Nivernais',
  'Griffonese',
  'Griffonland',
  'Griffonese',
  'Griffonshire',
  'Groenendael Chow',
  'Guatemalan Bull Terrier',
  'Hairless Khala',
  'Halden Hound',
  'Hamilton Hound',
  'Hare Indian Dog',
  'Harlequin Pinscher',
  'Harrier',
  'Hava-Apso',
  'Hava-Boston',
  'Hava-Jack',
  'Hava Klee',
  'Hava-Wheat',
  'Havachin',
  'Havachon',
  'Havallon',
  'Havamalt',
  'Havanese',
  'Havanestie',
  'Havapeke',
  'Havashire',
  'Havashu',
  'Havaton',
  'Hawaiian Poi Dog',
  'Hellenikos Ichnilatis',
  'Highland Maltie',
  'Himalayan Sheepdog',
  'Hovawart',
  'Hovie Gold Retriever',
  'Hug',
  'Hush Basset',
  'Huskimo',
  'Huskita',
  'Husky Jack',
  'Husky Wheaten',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Imo-Inu',
  'Indian Spitz',
  'Irish Afghan Setter',
  'Irish Bostetter',
  'Irish Boston Terrier',
  'Irish Dane',
  'Irish Doodle',
  'Irish Glen Imaal Terrier',
  'Irish Jack Terrier',
  'Irish Lakeland Terrier',
  'Irish Mastiff',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Staffordshire Bull Terrier',
  'Irish Terrier',
  'Irish Troodle',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Irish Wolf Greyhound',
  'Irish Wolf Setter',
  'Irish Wolfsky',
  'Istrian Shorthaired Hound',
  'Italian-Bichon',
  'Italian Border Greyollie',
  'Italian Bulldogge',
  'Italian Cairn',
  'Italian Daniff',
  'Italian Doxie',
  'Italian Eskimo',
  'Italian Greagle',
  'Italian Grey Min Pin',
  'Italian Greyenji',
  'Italian Greycrested',
  'Italian Greyhound',
  'Italian Greyhuahua',
  'Italian Papihound',
  'Italian Tzu',
  'Jacairn',
  'Ja-Chon',
  'Jack Chi',
  'Jack Highland Terrier',
  'Jack Pit',
  'Jack Russell Greyhound',
  'Jack Russell Terrier',
  'Jack Tzu',
  'Jack-A-Bee',
  'Jack-A-Poo',
  'Jack-A-Ranian',
  'Jackie-Bichon',
  'Jack-Rat Terrier',
  'Jackshund',
  'Jackweiler',
  'Jafox',
  'Jagdterrier',
  'Jaland',
  'Japanese Chow Spitz',
  'Japanese Spaniel (Chin)',
  'Japanese Spitz',
  'Japanese Spitz Chi',
  'Japanese Terrier',
  'Japanese Thai Ridgespitz',
  'Japeke',
  'Japillon',
  'Japug',
  'Jarkie',
  'Jatese',
  'Jatzu',
  'Jindo',
  'Jug',
  'Kai Dog',
  'Kangal Dog',
  'Kangaroo Dog',
  'Kanni',
  'Karelian Bear Dog',
  'Karst Shepherd',
  'Kashon',
  'Kattai Nai',
  'Keeshond',
  'Kelpie Corgi',
  'Kelpie Heeler',
  'Kelpie Lab',
  'Kelpie Shepherd',
  'Kelpie Staff',
  'Kemmer Feist',
  'Kemmer Stock Hybrid Squirrel Dog',
  'Kerry Blue Terrier',
  'Kerry Wheaten',
  'Kimola',
  'King Cavrin',
  'King Charles Yorkie',
  'King Pin',
  'King Rat',
  'King Schnauzer',
  'King Shepherd',
  'King Wheaten',
  'Kishu Ken',
  'Klein Poodle',
  'Kobetan',
  'Kokoni',
  'Komba',
  'Komondor',
  'Kooikerhondje',
  'Koolie',
  'Korean Dosa Mastiff',
  'Kugsha Dog',
  'Kukkal',
  'Kunming Dog',
  'Kuvasz',
  'Kyi-Leo',
  'Lab Aire',
  'Lab Apso',
  'Lab Pei',
  'Lab-Pointer',
  'Labahoula',
  'Labany',
  'Labbe',
  'Labernard',
  'Labernese',
  'Labloodhound',
  'Labmaraner',
  'Labollie',
  'Labrabull',
  'Labradane',
  'Labradinger',
  'Labradoodle',
  'Labrador Corso',
  'Labrador Husky',
  'Labrador Retriever',
  'Labraheeler',
  'Labrahuahua',
  'Labrakita',
  'Labralas',
  'Labrasenji',
  'Labrastaff',
  'Labrottie',
  'Lacasapoo',
  'La-Chon',
  'Lagotto Romagnolo',
  'Laizhou Hong',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Landseer',
  'Lapinporokoira',
  'La Pom',
  'Lapphund',
  'Lapponian Herder',
  'Large Münsterländer',
  'Larson Lakeview Bulldogge',
  'Latvian Hound',
  'Leavitt Bulldog',
  'LeoBerner',
  'Leonberger',
  'Leopard Cur',
  'Lha-Basset',
  'Lha-Cocker',
  'Lhaffon',
  'Lhasa Apso',
  'Lhasa-Corgi',
  'Lhasa-Coton',
  'Lhasa Jack',
  'Lhasa Vendeen',
  'Lhasalier',
  'Lhasanese',
  'Lhasapoo',
  'Lhatese',
  'Lithuanian Hound',
  'Llewellin Setter',
  'Louisiana Catahoula Leopard Dog',
  'Löwchen (Little Lion Dog)',
  'Lucas Terrier',
  'Lurcher',
  'Magyar Agar (Picture needed)',
  'Majestic Tree Hound',
  'Malamute Pei',
  'Malchi',
  'Malinois Akita',
  'Malinois Mastiff',
  'Mally Foxhound',
  'Mal-Shi',
  'Malteagle',
  'Maltese',
  'Maltichon',
  'Malti-Pin',
  'Maltipom',
  'Malti-Poo',
  'Malti-Pug',
  'Malti-Py',
  'Malton',
  'Mammut Bulldog',
  'Manchester Terrier',
  'Mandai Sheephound',
  'Maremma Kelpie',
  'Maremma Sheepdog',
  'Maremma Shepherd',
  'Markiesje',
  'Mastador',
  'Masti-Bull',
  'Mastidoodle',
  'Mastiff',
  'Mastiff Shepherd',
  'Mauxie',
  'Mauzer',
  'McNab',
  'Meagle',
  'Medium Poodle',
  'Mi-Ki',
  'Mini Australian Shepterrier',
  'Mini Cairn Pin',
  'Mini Coonhound',
  'Mini English Cocker',
  'Mini Fo-Chon',
  'Mini Foxillon',
  'Mini Foxy Russell',
  'Mini Kerry Blue Schnauzer',
  'Mini Schnauzer Jack',
  'Mini St. Bernard',
  'Mini Texas Heeler',
  'Miniature Aussiedoodle',
  'Miniature Australian Bulldog',
  'Miniature Australian Shepherd',
  'Miniature Border Schnollie',
  'Miniature Boxer',
  'Miniature Bulldog',
  'Miniature English Bulldach',
  'Miniature English Bulldog',
  'Miniature Fox Terrier',
  'Miniature French Bull Terrier',
  'Miniature French Schnauzer',
  'Miniature Golden Retriever',
  'Miniature Goldendoodle',
  'Miniature Labradoodle',
  'Miniature Pinscher',
  'Miniature Poodle',
  'Miniature Schnaupin ',
  'Miniature Schnauzer',
  'Miniature Schnauzzie',
  'Miniature Schnoxie',
  'Miniature Shar-Pei',
  'Miniboz',
  'Minnie Jack',
  'Minnie Parson',
  'Mi-orkie',
  'Mioritic Sheepdog',
  'Mollett Victorian Bulldog',
  'Molossus',
  'Mongrel (Mutt)',
  'Montaimboeuf',
  'Morkie',
  'Morkshire Terrier',
  'Moscow Vodolaz',
  'Moscow Watchdog',
  'Moscow Water Dog',
  'Mountain Bulldog',
  'Mountain Cur',
  'Mountain Cur Shepherd',
  'Mountain Feist',
  'Mountain Jack Cur',
  'Mountain Mastiff',
  'Mountain View Cur',
  'Mucuchies',
  'Mudi',
  'Muggin',
  'Mullins Feist',
  'Munsterlander',
  'Muscle Mastiff',
  'Native American Indian Dog',
  'Native American Shepherd',
  'Native American Village Dog',
  'Neapolitan Boxer',
  'Neapolitan Mastiff',
  'Neapolitan Shepherd',
  'Nebolish Mastiff',
  'Nehi Saint Bernard',
  'Neo Bullmastiff',
  'New Guinea Singing Dog',
  'New Shep',
  'New Zealand Heading Dog',
  'New Zealand Huntaway',
  'Newfie Dane',
  'Newfoundland',
  'Newfypoo',
  'Norrbottenspets',
  'Norfolk Spaniel',
  'Norfolk Terrier',
  'Nortese',
  'North Country Beagle',
  'Northern Inuit Dog',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck-Tolling Retriever',
  'Ol Southern Catchdog',
  'Old Anglican Bulldogge',
  'Old Danish Chicken Dog',
  'Old Deerhound Sheepdog',
  'Old Doxie Sheepdog',
  'Old English Sheepdog (Bobtail)',
  'Olde Boston Bullchi',
  'Olde Boston Bulldogge',
  'Olde Double Bully',
  'Olde English Bulldogge',
  'Olde Pit Bulldogge',
  'Olde Staff Bulldogge',
  'Olde Staffybull Bulldogge',
  'Olde Victorian Bulldogge',
  'Ori Pei',
  'Original English Bulldogge',
  'Original Mountain Cur',
  'Otterhound',
  'Otto Bulldog',
  'Paisley Terrier',
  'Pakistani Bull Dog (Gull Dong) ',
  'Pakistani Bull Terrier (Pakistani Gull Terr)',
  ' Pakistani Mastiff (Pakisani Bully Kutta)',
  ' Pakistani Shepherd Dog (Bhagyari Kutta)',
  'Panda Shepherd',
  'Pandikona',
  'Papastzu',
  'Paperanian',
  'Papichon',
  'Papigriffon',
  'Papijack',
  'Papillon',
  'Papimo',
  'Papi-poo',
  'Papitese',
  'Papshund',
  'Pariah Dog',
  'Parnell Carolina Cur',
  'Parson Russell Terrier',
  'Parsonhund',
  'Patterdale Doxie',
  'Patterdale Shepherd',
  'Patterdale Terrier',
  'Patterjack',
  'Patterland Terrier',
  'Patti',
  'Patton Terrier',
  'Peagle',
  'Peek-A-Pom',
  'Pek-A-Rat',
  'Peka-A-West',
  'Pekalier',
  'Pekarin',
  'Peke-A-Chon',
  'Peke-A-Chow',
  'Peke-A-Jack',
  'Peke-A-Pap',
  'Peke-A-Pin',
  'Peke-A-Tese',
  'Pekehund',
  'Peke-Italian',
  'Pekepoo',
  'Pekingese',
  'Pembroke Cocker Corgi',
  'Pembroke Corgi Pointer',
  'Pembroke Sheltie',
  'Pembroke Welsh Corgi',
  'Perdiguero de Burgos',
  'Perro de Presa Mallorquin',
  'Perro Ratonero Andaluz',
  'Persian Sarabi Dog',
  'Peruvian Inca Orchid (PIO)',
  'Petit Basset Griffon Vendeen',
  'Petit Bleu de Gascogne',
  'Petite Goldendoodle',
  'Petite Labradoodle',
  'Pharaoh Hound',
  'Pharaoh Lab',
  'Phu Quoc Ridgeback Dog',
  'Pineranian',
  'Pinny-Poo',
  'Pin-Tzu',
  'Pit Boodle',
  'Pit Heeler',
  'Pit Pei',
  'Pit Pin',
  'Pitsky',
  'Pitweiler',
  'Plica',
  'Plotkita',
  'Plottahoula',
  'Plott Hound',
  'Plott Rottie',
  'Plott Walker',
  'Plummer Terrier',
  'Pocket Beagle',
  'Pocket Pitbull',
  'Pointer',
  'Pointer Bay',
  'Pointer Pit',
  'Polish Hound',
  'Polish Lowland Sheepdog',
  'Polish Tatra Sheepdog',
  'Pom Terrier',
  'Pom-A-Nauze',
  'Pomapoo',
  'Pom-A-Pug',
  'Pomchi',
  'Pom-Coton',
  'Pomeagle',
  'Pomeranian',
  'Pomerat',
  'Pomimo',
  'Pom-Kee',
  'Pom-Shi',
  'Pom-Silk',
  'Pomsky',
  'Pomston',
  'Poochin',
  'Poodle',
  'Poogle',
  'Poolky',
  'Poos',
  'Poo-Shi',
  'Pootalian',
  'Poo-Ton',
  'Poovanese',
  'Porcelaine',
  'Portuguese Podengo',
  'Portuguese Pointer',
  'Portuguese Sheepdog',
  'Portuguese Water Dog',
  'Posavac Hound',
  'Poshies',
  'Potsdam Greyhound',
  'Powderpap',
  'Prazsky Krysavik',
  'Presa Canario',
  'Presa Dane',
  'Pudelpointer',
  'Pug',
  'Pugairn',
  'Pugalier',
  'Pug-A-Mo',
  'Pugapoo',
  'Pug-Coton',
  'Pug Pit',
  'Pug Shiba',
  'Pug-Zu',
  'Pugese',
  'Puggat',
  'Puggit',
  'Puggle',
  'Pughasa',
  'Pugillon',
  'Puginese',
  'Pugland',
  'Pugmatian',
  'Pugottie',
  'Pugshire',
  'Pugwich',
  'Puli (Pulik)',
  'Pumi',
  'Pungsan Dog',
  'Pushon',
  'Pyrador',
  'Pyredoodle',
  'Pyrenean Mastiff',
  'Pyrenees Husky',
  'Pyrenees Pit',
  'Pyrenean Shepherd',
  'Queen Elizabeth Pocket Beagle',
  'Rafeiro do Alentejo',
  'Raggle',
  'Rajapalayam',
  'Rampur Greyhound',
  'Rashon',
  'Rat-A-Pap',
  'Rat Apso',
  'Rat Basset',
  'Rat-Cha',
  'Rat Feist',
  'Rat Heeler',
  'Ratmatian',
  'Rat Pei',
  'Rat Terrier',
  'Ratahoula',
  'Ratese',
  'Ratshi Terrier',
  'Ratshire Terrier',
  'Rattle',
  'Rattle Griffon',
  'Reagle',
  'Redbone Coonhound',
  'Redbone Lab',
  'Redbone Shepherd',
  'Red-Tiger Bulldog',
  'Red Wolf',
  'Rhodesian Beagle',
  'Rhodesian Bernard',
  'Rhodesian Boxer',
  'Rhodesian Collie',
  'Rhodesian Labrador',
  'Rhodesian Pit',
  'Rhodesian Ridgeback',
  'Rhodesian Rottie',
  'Rhodesian Shepherd',
  'Rhodesian Whippet',
  'Roman Rottweiler',
  'Romanian Mioritic Shepherd Dog',
  'Rott Pei',
  'Rottaf',
  'Rotterman',
  'Rotticorso',
  'Rottie Basset',
  'Rottie Bordeaux',
  'Rottie Chow',
  'Rottie Cocker',
  'Rottie Corgi',
  'Rottie Heeler',
  'Rottle',
  'Rottmatian',
  'Rottsky',
  'Rottweiler',
  'Rumanian Sheepdog',
  'Rus-A-Pei',
  'Russian Hound',
  'Russian Bandog',
  'Russian Spaniel',
  'Russian Toy',
  'Russian Tsvetnaya Bolonka',
  'Russo-European Laika',
  'Rustralian Terrier',
  'Saarlooswolfhond',
  'Sabueso Español',
  'Sage Ashayeri',
  'Saint Berdoodle',
  'Saint Bermastiff',
  'Saint Bernard',
  'Saint Bernese',
  'Saint Bernewfie',
  'Saint Chesa Bay Bernard',
  'Saint Dane',
  'Saint Pyrenees',
  'Saint Shepherd',
  'Salish Woolly Dog',
  'Saluki',
  'Saluki Deerhound',
  'Saluki Greyhound',
  'Saluki Sloughi',
  'Sammy Chow',
  'Sammy Shepherd',
  'Samollie',
  'Samoyed',
  'Samusky',
  'Sarplaninac',
  'Sceagle',
  'Schapendoes',
  'Schapso',
  'Schip-A-Pom',
  'Schip Coton',
  'Schipese',
  'Schipper-Chi',
  'Schipperke',
  'Schipper-Pin',
  'Schipper-Poo',
  'Schnairedale',
  'Schnau-Tzu',
  'Schnauzador',
  'Schnauzer',
  'Schnauzer Pit',
  'Schneagle',
  'Schnekingese',
  'Schnese',
  'Schnocker',
  'Schnoodle',
  'Schnug',
  'Schweenie',
  'Scobo Terrier',
  'Scoland Terrier',
  'Scolden Terrier',
  'Scoodle',
  'Scorkie',
  'Sco-Shi',
  'Scotch Collie',
  'Scotch Terrier',
  'Scotchi',
  'Scotchon',
  'Scotti Apso',
  'Scottie Schnauzer',
  'Scottish Cocker',
  'Scottish Deerhound',
  'Scottish Deer Greyhound',
  'Scottish Terrier (Scottie)',
  'Scottish-Skye Terrier',
  'Sealydale Terrier',
  'Sealyham Terrier',
  'Segugio Italiano',
  'Seidenspitz',
  'Seppala Siberian Sleddog',
  'Sharberian Husky',
  'Sharbo',
  'Sharmatian',
  'Sharp Eagle',
  'Shar-Pei',
  'Shar-Poo',
  'Shar Tzu',
  'Sheepadoodle',
  'Shel-Aussie',
  'Shelchon',
  'Shelestie',
  'Shelillon',
  'Sheltidoodle',
  'Sheltie Heeler',
  'Sheltie Inu',
  'Sheltie Pin',
  'Sheltie Pug',
  'Sheltie Shepherd',
  'Sheltie Tzu',
  'Shepadoodle',
  'Shepherd Pei',
  'Shepherd Pit',
  'Shepherd Tzu',
  'Shepnees',
  'Sheprador',
  'Sheptese',
  'Shepweiler',
  'Shetland Sheepdog (Sheltie)',
  'Shiba-Chi',
  'Shiba Corgi',
  'Shiba Inu',
  'Shiba Lab',
  'Shibos',
  'ShiChi',
  'Shichon',
  'Shiffon',
  'Shih Apso',
  'Shih Tzu',
  'Shih-Mo',
  'Shih-Poo',
  'Shikoku',
  'Shiloh Shepherd',
  'Shinese',
  'Shiranian',
  'Shocker',
  'Shockerd',
  'Shollie',
  'Shorgi',
  'Shorkie Tzu',
  'Shorty Bull',
  'Shug',
  'Sibercaan',
  'Siberian Boston',
  'Siberian Cocker',
  'Siberian Collisky',
  'Siberian Husky',
  'Siberian Indian Dog',
  'Siberian Kelpsky',
  'Siberian Retriever',
  'Siberian Shiba',
  'Siberpoo',
  'Silkchon',
  'Silken Windhound',
  'Silkese',
  'Silkin',
  'Silkinese',
  'Silkland Terrier',
  'Silkshire Terrier',
  'Silkshund',
  'Silky Cairn',
  'Silky Cocker',
  'Silky Coton',
  'Silky Jack',
  'Silky Pug',
  'Silky Terrier',
  'Silky Tzu',
  'Silkyhuahua',
  'Silky-Lhasa',
  'Silky-Pin',
  'Silkzer',
  'Simaku',
  'Ski-Border',
  'Skilky Terrier',
  'Skip-Shzu',
  'Skye-Pap',
  'Skye Terrier',
  'Skypoo',
  'Sloughi',
  'Slovakian Hound',
  'Slovakian Rough Haired Pointer',
  'Slovakian Wirehaired Pointer',
  'Slovensky Kopov',
  'Slovensky Cuvac',
  'Smalandsstovare',
  'Small Greek Domestic Dog',
  'Small Munsterlander',
  'Small Swiss Hound',
  'Smooth Fox Terrier',
  'Smooth Foxy Boerboel',
  'Smooth Foxybull Terrier',
  'Smooth Poxer',
  'Sniffon',
  'Snorkie',
  'Soft Coated Golden',
  'Soft Coated Wheaten Terrier',
  'Soft Coated Wheatzer',
  'Soft Coated Woxer',
  'South Russian Ovtcharka',
  'Southern Hound',
  'Spanador',
  'Spangold Retriever',
  'Spanish Mastiff',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Spreagle',
  'Springer Basset',
  'Springer Husky',
  'Springer Pit',
  'Springer Rottie',
  'Springerdoodle',
  'Sprocker Spaniel',
  'Sprollie',
  'St. John Water Dog',
  'St. Weiler',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Staffy Bull Bordeaux',
  'Staffy Bull Bullmastiff',
  'Staffy Bull Pei',
  'Staffy Bull Pit',
  'Staffy Bull Pug',
  'Staffy Bull Wolfhound',
  'Staffy Heeler',
  'Staffy Pit',
  'Staghound',
  'Standard Auss-Tzu',
  'Standard Border Schnollie',
  'Standard Chesa-Poo',
  'Standard Poodle',
  'Standard Schnauzer',
  'Standard Schnoodle',
  'Standard Siberian Schusky',
  'Stephens Stock Mountain Cur',
  'Sussex Spaniel',
  'Swedish Lapphund',
  'Swedish Vallhund',
  'Swiss Laufhund ',
  'Swiss Newfie',
  'Swiss Shorthaired Pinscher ',
  'Swissneese',
  'Swissy Saint',
  'Taco Terrier',
  'Tahltan Bear Dog',
  'Taigan',
  'Taiwan Dog',
  'Talbot',
  'Tamaskan Dog',
  'Tangkhul Hui',
  'Taylors Minidane',
  'Teacup Poodle',
  'Teddy Roosevelt Terrier',
  'Telomian',
  'Tenterfield Terrier',
  'Terri-Poo',
  'Tesem',
  'Texas Heeler',
  'Thai Bangkaew Dog',
  'Thai Boxridge',
  'Thai Ridgeback',
  'Thornburg Feist',
  'Thylacine',
  'Tibalier',
  'Tibetan Chin',
  'Tibetan Golden Mastiff',
  'Tibetan Mastiff',
  'Tibetan Pap',
  'Tibetan Pom',
  'Tibetan Pug',
  'Tibetan Spaltese',
  'Tibetan Spaniel',
  'Tibetan Staffy Spaniel',
  'Tibetan Terrier',
  'Timber Wolf',
  'Titan Bull-Dogge',
  'Titan Terrier',
  'Toller Pit',
  'Torkie',
  'Tornjak',
  'Tosa Inu',
  'Tosa-Pei',
  'Toxirn',
  'Toy Bulldog',
  'Toy Fo-Chon',
  'Toy Fox Beagle',
  'Toy Fox Pinscher',
  'Toy Fox Terrier',
  'Toy Foxie Doxie',
  'Toy Foxillon',
  'Toy Foxingese',
  'Toy Foxker',
  'Toy Poodle',
  'Toy Poxer',
  'Toy Rat Doxie',
  'Toy Trawler Spaniel',
  'Transylvanian Hound',
  'Treeing Cur',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Turkish Yellow Dog',
  'Turnspit Dog',
  'Tweed Water Spaniel',
  'Tzu Basset',
  'Ultimate Mastiff',
  'Utonagan',
  'Valley Bulldog',
  'Vanguard Bulldog',
  'Victorian Boston Bulldog',
  'Victorian Bulldog',
  'Villano de Las Encartaciones',
  'Vizmaraner',
  'Vizsla',
  'Vizsla Pin',
  'Vucciriscu',
  'Walker Beagle',
  'Wauzer',
  'Wee-Chon',
  'Weeranian',
  'Weiler Dane',
  'Weimaraner',
  'Weimardoodle',
  'Weimarman',
  'Weim-Pei',
  'Wel-Chon',
  'Welsh Corgi',
  'Welsh Sheepdog',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'Weshi',
  'West Highland Doxie',
  'West Highland Husky',
  'West Highland White Terrier (Westie)',
  'West of Argyll Terrier',
  'West Siberian Laika',
  'Westeke',
  'Western Mountain Cur',
  'Westie Staff',
  'Westie-Laso',
  'Westiepoo',
  'Westillon',
  'Westimo',
  'Weston',
  'Wetterhoun',
  'Wheaten Pei',
  'Whipador',
  'Whipperman',
  'Whippet',
  'Whippet Greyhound',
  'White Bloodhound',
  'White English Bulldog',
  'Whoodle',
  'Wire Fox Pinscher',
  'Wire Foxker',
  'Wire Hair Snauzer',
  'Wirehaired Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Wirelsh Terrier',
  'Wire-Poo',
  'Wolador',
  'Wolamute',
  'Wolf Hybrid',
  'Wolfdog',
  'Woodle',
  'Wowauzer',
  'Xoloitzcuintle',
  'Yakutian Laika',
  'Yoranian',
  'Yorkie Pin',
  'Yorkie Russell',
  'Yorkie-Apso',
  'Yorkie-ton',
  'Yorkillon',
  'Yorkinese',
  'Yorkipoo',
  'Yorkshire Terrier',
  'Yorksky',
  'Yorktese',
  'Yorwich',
  'Yugoslavian Hound',
  'Zuchon',
  'About Dog Breed Info Center®',
  'Natural Dogmanship',
  'Success Stories & Positive Feedback',
  'Maguire Farm',
  'Fiberglass Awareness',
  'Unknown',
];
